### ISSUE TITLE
test wizard

### ISSUE THREAD

**Issue by baf139** [psudug/nittany-vagrant#14]
I have a wizard in place could you test it? I only have one recipe to run right now... but will have more soon. thanks.

**Comment by baf139** [comment]
oh yeah i had to change the order of execution a touch ... i hope that doesn't cause any issues for me it didn't. drush path needs to be in place before the rest of the home setup so wizard knows where it is.

**Comment by btopro** [comment]
if you source .bashrc it should refresh that throughout the execution. nothing wrong in what your doing as far as I can tell; just saying that's how I get that into scope.

**Comment by baf139** [comment]
same file top down order is the issue and it is solved.
