### ISSUE TITLE
provisioner doesn't run properly in windows

### ISSUE THREAD

**Issue by AndrewGearhart** [psudug/nittany-vagrant#18]
It seems that the provisioner doesn't run properly in Windows 7. This makes baby Jesus cry. It seems to fail around the time that the all is made to run the bash scripts with "bash" ...

**Comment by baf139** [comment]
what is the error?

**Comment by AndrewGearhart** [comment]
Seems that it was an issue with Git for Windows deciding that line endings on a windows box should be adjusted to be "correct" for a windows box. Adding .gitattributes forces Git for Windows not to do this for this repository. Fixed with fcbe915e9f3b42f428400f412a48a1863174d9e6
