### ISSUE TITLE
Questions need asked

### ISSUE THREAD

**Issue by btopro** [psudug/nittany-vagrant#2]
after logging in it should prompt you with an sh script / recipes that step through requiring your input in order to build out more of the site automatically ahead of time

**Comment by baf139** [comment]
So it should probably kill the script after it runs so it doesn't run each time you log in.

**Comment by baf139** [comment]
i will just set up logic to follow and we can figure out what recipes to run later.

**Comment by baf139** [comment]
stubbed  - just needs the right recipes which i will be doing later tonight and through the week... currently seo is in place since https://github.com/psudug/nittany gets cloned on vagrant up.

**Comment by btopro** [comment]
looks good to me, we've got questions and tested after adding some additional questions to ask :)
