### ISSUE TITLE
Apply and h5bp server configs and increase optimization OOTB

### ISSUE THREAD

**Issue by btopro** [psudug/nittany-vagrant#21]
I think we need a combination of recipes, configuration and directions on how people can get 100/100 google page speed score. @bradallenfisher was recently able to achieve this, breaking our previous best records in the neighborhood of 92. It would be great to automate this so it Just Happens tm

**Comment by btopro** [comment]
https://github.com/h5bp/server-configs-apache and mod_pagespeed should be brought into the fold automatically when establishing the server. We already do some optimizations but would rather us align with a group specifically focused on it.

**Comment by AndrewGearhart** [comment]
+1 to piggybacking on someone else who is doing these optimizations as long as they can continue to be automated.

**Comment by btopro** [comment]
@AndrewGearhart we're doing some level of forced optimization to apache, php, apc and mysql right now. We'd just need to switch over to their method of forced optimization to apache as well as see if what we do currently is any better then what they are doing; they have a lot of other tricks up their sleeves in that repo too :)

**Comment by baf139** [comment]
@btopro and @AndrewGearhart I think we should break out the files we have in favor of the way h5bp is doing things. Easier to digest should more techniques pop up.

**Comment by baf139** [comment]
I think this is done. reopen if not.
