### ISSUE TITLE
No content-types

### ISSUE THREAD

**Issue by noesnaterse** [psudug/nittany-vagrant#38]
I just launched a site in Vagrant, but there are no content-types.

There are links for adding a blog post, a project, and a course, but the actual content-types aren't present.
This means that when I click any of the add links, I get redirected to http://nittany.psudug.dev/node/add/node_export

**Comment by btopro** [comment]
go to the features page and make sure the publicize features are enabled; clear caches.

**Comment by noesnaterse** [comment]
That was it, thanks.
