### ISSUE TITLE
Provisioner scripts to pull down from production

### ISSUE THREAD

**Issue by btopro** [psudug/nittany-vagrant#5]
Need to add in @bradallenfisher 's provisioning scripts to pull sites down into the VM for testing, back up, etc.

**Comment by baf139** [comment]
my way involves ssh-keys to the server you are pulling from... so git for core and modules and drush sql-sync and rsync for %files and db. 

should add aliases, ssh-keygen, ssh-copy-id instructions, and have the script in there that needs edited?
this might require some discussion.

**Comment by btopro** [comment]
supply ways of doing it for sure, then we can react to the methods employed; when you get into ssh keygen stuff it might be a little more difficult to automate completely (tho I'd sure love to) :)

**Comment by btopro** [comment]
I've added ssh key gen stuff as an option but I lost my stuff that did all the questions / input for the actual key binding to a remote server :) as @bradallenfisher brought up, how much hand holding can we do. So, for now we're at least telling them the shortcut command to do the remote key copy

**Comment by baf139** [comment]
When running the option: 4 i get some errors

Would you like to install drupal? (y/n) y
Glad to hear it, let's get started by installing drupal
/vagrant/scripts/drupal/distros/1-core-drupal.sh
Available options:
1 # Standard install
2 # Publicize distribution
3 # (Advanced) Build a distro from a repo
4 # (Expert) Pull down from server
Enter an option: 4
This is going to establish a connection to a real server you have, then pull down the code and database in question and mirror it locally so you can work off-line.
If these things sound scary then you probably shouldn't use this mode as its fairly advanced!
What server do you want to connect to? 172.29.77.35
What user name? baf139
What port (usually 22 / 2222 are common)? 22
myname@mynumbers's password: 
Now try logging into the machine, with "ssh '-p NN my_name@nn.nn.nn.nn", and check in:

  .ssh/authorized_keys

to make sure we haven't added extra keys that you weren't expecting.

Where is this site (include trailing slash)? /var/www/sites/thesiteichose/
making a database dump of the remote system
Database dump saved to ~/nittany.sql                                   [success]
rsyncing down from remote source, might take awhile...
receiving incremental file list
nittany.sql
receiving incremental file list
nittany.sql

sent 30 bytes  received 12331304 bytes  3523238.29 bytes/sec
total size is 21464475  speedup is 1.74
You are about to create a sites/default/settings.php file and CREATE  the 'nittany' database. Do you want to continue? (y/n): y
copy(sites/default/default.settings.php): failed to open stream: No such file or directory drush.inc:692                                            [warning]
Failed to copy sites/default/default.settings.php to  sites/default/settings.php                                                                    [error]
No database to operate on.                                                                                                                          [error]
No database to operate on.                                                                                                                          [error]
Query failed.

**Comment by baf139** [comment]
I'm wondering if it doesn't like that we put stuff in /var/www/sites instead of /var/www/html?

**Comment by btopro** [comment]
Did you have a trailing slash?

WP8 mobile

**Comment by btopro** [comment]
or rsync didnt have perms to copy everything

**Comment by baf139** [comment]
yeah i think permissions. I had the slash... fresh vagrant up trying again.

**Comment by baf139** [comment]
actually, the issue here is that we delete our default.settings.php files in our prod sites.

**Comment by btopro** [comment]
sounds like a good thing to check for then to add it in from d.o.

**Comment by baf139** [comment]
this works for normal installations of drupal.
